ARG GOLANG_VERSION="latest"

FROM golang:${GOLANG_VERSION}

ENV GO_ENV="test"

LABEL maintainer="Devajit Asem"

WORKDIR $GOPATH/src/hayum/core_apis

COPY . .

RUN GO111MODULE=on go get -d ./...

RUN go test ./... -tags=integration 