ARG GOLANG_VERSION="latest"

FROM golang:${GOLANG_VERSION}

ENV GO_ENV=test
ENV GO111MODULE=on

LABEL maintainer="Devajit Asem"

WORKDIR $GOPATH/src/hayum/core_apis

COPY . .

CMD go test ./... -tags=integration