version: "3"

services:
  hayum:
    container_name: hayum_core
    build:
      context: .
      dockerfile: ./deployments/Dockerfile
      args:
        ENV: development
    image: hayum:latest
    ports:
      - 8080:8080
    restart: on-failure
    networks:
      - integration-tests
  mysql:
    container_name: mysql_dev
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=hayum_dev
      - MYSQL_ROOT_PASSWORD=devmysql
    ports:
      - 3306:3306
    networks:
      - integration-tests

networks:
  integration-tests:
    driver: bridge