port: :8080

logpath: /var/log/hayum/log.txt

db:
  dev:
    url: localhost
    port: 27017
    name: hayum
  test:
    name: test_hayum

s3:
  bucket: test-hy
  directory: tracks

# 30 days!!!
sessionExpirationTimeInMS: 2592000000 