port: :8080

logpath: /var/log/hayum/log.txt

db:
  url:
  user: root
  password: devmysql
s3:
  bucket: dev-hy
  directory: tracks

# 30 days!!!
session:
  table_name: Session
  expiration_time_ms: 3600
  # it will be persisted externally in production environment
  secret_key: 8s$#kslsd120981293
